@startuml

left to right direction

Admin    <<operator>> as admin

rectangle "Users Management" {
  (List users) as listUsers
  (Edit user details) as editUser
  (authentication) as auth
}

admin -> listUsers
admin -> editUser

listUsers ..> auth : <<include>>
editUser ..> auth : <<include>>

@enduml
