@startuml

Admin    <<operator>> as admin
User     <<operator>> as user

admin --|> user : <<extends>>

(Add user) as addUser
(List users) as listUsers
(Edit user details) as editUser
(authentication) as auth

admin -> listUsers
admin -> editUser
user -> addUser

listUsers ..> auth : <<include>>
editUser ..> auth : <<include>>

@enduml
