@startuml
left to right direction

User    <<operator>> as user

rectangle "Products Management" {
  (List tasks) as listTasks
  (Edit task) as editTask
  (Mark task as done) as markDone
  (authentication) as auth
}

user --> listTasks
user --> editTask
user --> markDone

listTasks ..> auth : <<include>>
editTask ..> auth : <<include>>
markDone ..> auth : <<include>>

@enduml
