@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as user
actor System                as system
actor Database              as db

user  -> system  : ask for /users/create
system --> user : display form
user -> system : enter user informations
system -> system  : create User object from datas
system -> system  : check if user is valid
alt User is valid
    system -> db      : Persist User object
    system <-- db     : return data
    user  <-- system : return 201 status code
else
    user  <-- system : return 400 status code
end
@enduml