@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Authenticated client" as client
actor System                as system
actor Database              as db

client  -> system  : send HTTP GET /api/users
system -> db      : request for client's users list
system <-- db     : return data
client  <-- system : return clients list in JSON

@enduml