@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Authenticated admin" as admin
actor System                as system
actor Database              as db

admin  -> system  : go to /users
system -> db      : request for user list
system <-- db     : return data
admin  <-- system : return clients list

@enduml