@startuml
'https://plantuml.com/component-diagram

package "Application" {
  [Tasks Management]
  [Users Management]
  [Authentication]
}

[Tasks Management] ..> [Authentication] : extends
[Users Management] ..> [Authentication] : extends

@enduml